from enum import Enum

class InsertStatements(Enum):
    InsertTableKeys="INSERT INTO keys (El_NAME, El_ALGORITHM, El_LENGTH, El_VALUE, El_PRIV_KEY_VALUE, El_PUB_KEY_VALUE, El_CREATION_DATE) VALUES (?,?,?,?,?,?,?)"

class CreateStatements(Enum):
    CreateTableKeys="CREATE TABLE IF NOT EXISTS keys (El_ID INTEGER PRIMARY KEY AUTOINCREMENT, El_NAME VARCHAR(30) NOT NULL, El_ALGORITHM VARCHAR(30) NULL, El_LENGTH INTEGER NULL, El_VALUE BLOB NULL, El_PRIV_KEY_VALUE BLOB NULL, El_PUB_KEY_VALUE BLOB NULL, El_CREATION_DATE DATETIME NOT NULL)"